import React, { useEffect } from "react";

import "../../styles/text.css";

import bg from "../../images/BG.png";

export const BGimage = (props) => {
  const { updateBG } = props;

  useEffect(() => {
    updateBG(false);
  }, [updateBG]);
  return (
    <div className="page-container fade-in">
      {/* <ScrollingBackground /> */}
      <div className="img-container">
        <img src={bg} alt="music" />
        <p>
          A diagram of the nodes in the NetWorks algorithm provided by Bell and
          Gabora.
        </p>
        <p>
          Bell and Gabora have provided{" "}
          <a
            href="https://shawnbell.bandcamp.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            various albums
          </a>{" "}
          of music generated by NetWorks for public evaluation.
        </p>
      </div>
    </div>
  );
};
